version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=sqlite:///./test.db
    ports:
      - "8080:8080"
    volumes:
      - /workdir
    depends_on:
      - db

  db:
    image: "sqlite:latest"
    volumes:
      - /Users/linhth1/Documents/share_data:/app/test.db
